# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: DEVNCEINFCR1401.azurecr.io/defra/ncea-harvester-service
  tag: 20240425.10_feature-366449-send-message-after-saving-all-xml-files
  imagePullPolicy: IfNotPresent

serviceAccount:
  name: saccount-ncea-devnceinfid1404

env:
  serviceBusHostName: DEVNCESBINF1401.servicebus.windows.net
  keyVaultUri: https://devnceinfkvt1401.vault.azure.net/
  blobStorageUri: https://devnceinfst1401.blob.core.windows.net

jobs:    
  # cron job configurations for medin data source
  medin:    
    env:
    - name: DataSource
      value: "medin"

    schedule: "0 * * * *"
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    concurrencyPolicy: Forbid
    restartPolicy: OnFailure
    imagePullSecrets: []
  
  # cron job configurations for jncc data source
  jncc:    
    env:
    - name: DataSource
      value: "jncc"
    
    schedule: "0 * * * *"
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    concurrencyPolicy: Forbid
    restartPolicy: OnFailure
    imagePullSecrets: []
  