# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: $(containerRepositoryFullPath)
  tag: $(imageTag)
  imagePullPolicy: IfNotPresent

serviceAccount:
  name: $(serviceAccountHarvester)

env:
  serviceBusHostName: $(serviceBusHostName)
  keyVaultUri: $(keyVaultUri)
  blobStorageUri: $(blobStorageUri)

jobs:    
  # cron job configurations for medin data source
  medin:    
    env:
    - name: DataSource
      value: "medin"

    schedule: $(medinSchedule)
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    concurrencyPolicy: Forbid
    restartPolicy: OnFailure

    resources:
      requests:
        cpu: 100m
        memory: 250Mi
      limits:
        cpu: 200m
        memory: 500Mi
  
  # cron job configurations for jncc data source
  jncc:    
    env:
    - name: DataSource
      value: "jncc"
    
    schedule: $(jnccSchedule)
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    concurrencyPolicy: Forbid
    restartPolicy: OnFailure

    resources:
      requests:
        cpu: 100m
        memory: 250Mi
      limits:
        cpu: 200m
        memory: 500Mi
  