# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: $(containerRepositoryFullPath)
  tag: $(imageTag)
  imagePullPolicy: IfNotPresent

serviceAccount:
  name: $(serviceAccountHarvester)

env:
  serviceBusHostName: $(serviceBusHostName)
  keyVaultUri: $(keyVaultUri)
  blobStorageUri: $(blobStorageUri)

pv:
  storageAccountResourceGroup: $(storageAccountResourceGroup)
  storageAccountName: $(storageAccountName)
  storageAccountFilePrivateEndpointFqdn: $(storageAccountFilePrivateEndpointFqdn)
  enrichedMetadataShareName: metadata-import
  pvcSize: 10Gi

volumes: 
- name: enrichedmetadata
  persistentVolumeClaim:
    claimName: ncea-enricher-fileshare-pvc

volumeMounts: 
- mountPath: /metadata-import
  name: enrichedmetadata

jobs:    
  # cron job configurations for medin data source
  medin:    
    env:
    - name: DataSource
      value: "medin"

    schedule: $(medinSchedule)
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    concurrencyPolicy: Forbid
    restartPolicy: OnFailure
  
  # cron job configurations for jncc data source
  jncc:    
    env:
    - name: DataSource
      value: "jncc"
    
    schedule: $(jnccSchedule)
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    concurrencyPolicy: Forbid
    restartPolicy: OnFailure
  