# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: 
  tag: latest
  imagePullPolicy: IfNotPresent

serviceAccount:
  name: 

env:
  serviceBusHostName: 
  keyVaultUri: 
  blobStorageUri: 

jobs:    
  # cron job configurations for medin data source
  medin:    
    env:
    - name: DataSource
      value: "medin"

    schedule: "* 12 * * *"
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    concurrencyPolicy: Forbid
    restartPolicy: OnFailure
  
  # cron job configurations for jncc data source
  jncc:    
    env:
    - name: DataSource
      value: "jncc"
    
    schedule: "* 12 * * *"
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    concurrencyPolicy: Forbid
    restartPolicy: OnFailure
  