# Starter pipeline

name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - main
      - feature/*

pool:
  vmImage: 'ubuntu-latest'

variables
  ACR.Deploy: true
  ACR.ServiceConnection : acr-AZR-NCE-SND1
  acrName: nceapocsbox
  ACR.ContainerRepository: defra/ncea-harvester-service
  chartPath: src/ncea-harvester/charts/ncea-harvester

steps:
- template: steps-build-and-test.yml
- template: steps-build-and-push-docker-images.yml
- template: steps-build-and-push-helm-charts.yml