# Starter pipeline

name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - main
      - feature/* 

variables:
  - template: templates/variables-build.yml
    
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  isPullRequest: $[eq(variables['Build.Reason'], 'PullRequest')]
  branchSource: $[replace(variables['Build.SourceBranch'], 'refs/heads/', '')]
  branch: $[replace(variables['branchSource'], '/', '-')]
  ${{ if ne(variables.main, 'true') }}:
    artifactNameSuffix: _$(branch)
  ${{ else }}:
    artifactNameSuffix: ''
  chartPath: 'src/ncea-harvester/ncea-harvester'
  containerRespository: 'defra/ncea-harvester-service'
  imageTag: $(Build.BuildNumber)$(artifactNameSuffix)

stages:
- stage: 'Build'
  displayName: 'Build Harvester Service'
  jobs: 
  - job: 'Build'
    displayName: 'Build job'
    pool:
      vmImage: 'ubuntu-latest'
      
    steps:
      - template: steps-build-and-test.yaml
      - template: steps-build-and-push-docker-images.yaml
      - template: steps-package-and-push-helm-charts.yaml

- stage: 'sandbox'
  displayName: 'Deploy to Sandbox'
  dependsOn: Build
  condition:  and(succeeded(), eq(variables.isPullRequest, true))
  variables:
   - template: templates/variables-sandbox.yml
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    environment: sandbox 
    strategy:
      runOnce:
        deploy:
          steps:
            - template: steps-deploy-helm-charts.yaml
              parameters:
                envName: sandbox
                releaseName: ncea-harvester-sandbox

- stage: 'dev'
  displayName: 'Deploy to Dev'
  dependsOn: Build
  condition:  and(succeeded(), eq(variables.isMain, true))
  variables:
   - template: templates/variables-dev.yml
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    environment: dev 
    strategy:
      runOnce:
        deploy:
          steps:
            - template: steps-deploy-helm-charts.yaml
              parameters:
                envName: dev
                releaseName: ncea-harvester-dev