
name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - main
      - feature/* 

variables: 
  - template: templates/variables-global.yml
  - name : acrContainerRegistryServiceConnection
    value: acr-AZR-NCE-SND1

stages:
- stage: 'Build'
  displayName: 'Build Harvester Service'
  jobs: 
  - job: 'Build'
    displayName: 'Build job'
    pool:
      vmImage: 'ubuntu-latest'
    variables:
      - template: templates/variables-build.yml      
    steps:
      - template: steps-build-and-test.yaml
      - template: steps-build-and-push-docker-images.yaml
      - template: steps-package-and-push-helm-charts.yaml

- stage: 'sandbox'
  displayName: 'Deploy to Sandbox'
  dependsOn: Build
  condition:  and(succeeded(), eq(variables.isPullRequest, false))  
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    variables:
      - template: templates/variables-sandbox.yml
      - name : aksServiceConnection
        value: aksServiceConn-AZR-NCE-SND1
    environment: sandbox 
    strategy:
      runOnce:
        deploy:
          steps:
            - template: steps-deploy-helm-charts.yaml
              parameters:
                envName: sandbox
                releaseName: ncea-harvester-sandbox
                aksServiceConnection: aksServiceConn-AZR-NCE-SND1
                repository: $(acrContainerRegistry)/$(acrContainerRepositoryHarvester)

- stage: 'dev'
  displayName: 'Deploy to Dev'
  dependsOn: Build
  condition:  and(succeeded(), eq(variables.isMain, true))
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    variables:
      - template: templates/variables-dev.yml
    environment: dev 
    strategy:
      runOnce:
        deploy:
          steps:
            - template: steps-deploy-helm-charts.yaml
              parameters:
                envName: dev
                releaseName: ncea-harvester-dev
                aksServiceConnection: aksServiceConn-AZR-NCE-SND1
                repository: $(acrContainerRegistry)/$(acrContainerRepositoryHarvester)