{{- $repository := .Values.image.repository -}}
{{- $tag := .Values.image.tag -}}
{{- $imagePullPolicy := .Values.image.imagePullPolicy -}}
{{- $serviceAccountName := .Values.serviceAccount.name -}}

{{- $serviceBusHostName := .Values.env.serviceBusHostName -}}
{{- $keyVaultUri := .Values.env.keyVaultUri -}}
{{- $blobStorageUri := .Values.env.blobStorageUri -}}

{{- range $jobname, $job := .Values.jobs }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "cronjobs.releaseName" $ }}-{{ $jobname }}
  labels:
    azure.workload.identity/use: "true" 
    {{- include "cronjobs.labels" $ | nindent 4 }}
spec:
  concurrencyPolicy: {{ $job.concurrencyPolicy }}
  failedJobsHistoryLimit: {{ $job.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: {{ include "cronjobs.releaseName" $ }}
            cron: {{ $jobname }}
            azure.workload.identity/use: "true"
        spec:
        {{- if hasKey $job "imagePullSecrets" }}
          imagePullSecrets:
          - name: {{ $.Release.Name }}-docker
        {{- end }}
          serviceAccountName: {{ $serviceAccountName }}
        {{- if hasKey $job "securityContext" }}
          {{- if $job.securityContext.runAsUser }}
          securityContext:
            runAsUser: {{ $job.securityContext.runAsUser }}
            {{- if $job.securityContext.runAsGroup }}
            runAsGroup: {{ $job.securityContext.runAsGroup }}
            {{- end }}
            {{- if $job.securityContext.fsGroup }}
            fsGroup: {{ $job.securityContext.fsGroup }}
            {{- end }}
          {{- end }}
        {{- end }}
          containers:
          - image: {{ $repository }}:{{ $tag }}
            imagePullPolicy: {{ $imagePullPolicy }}
            name: {{ $jobname }}
            {{- with $job.env }}
            env:
{{ toYaml . | indent 12 }}
            {{- end }}
            - name: ServiceBusHostName
              value: {{ $serviceBusHostName }}
            - name: KeyVaultUri
              value: {{ $keyVaultUri }}
            - name: BlobStorageUri
              value: {{ $blobStorageUri }}
            {{- with $job.envFrom }}
            envFrom:
{{ toYaml . | indent 12 }}
            {{- end }}
            {{- with $job.command }}
            command:
{{ toYaml . | indent 12 }}
            {{- end }}
            {{- with $job.args }}
            args:
{{ toYaml . | indent 12 }}
              {{- end }}
            {{- with $job.resources }}
            resources:
{{ toYaml . | indent 14 }}
            {{- end }}
            {{- with $job.volumeMounts }}
            volumeMounts:
{{ toYaml . | indent 12 }}
            {{- end }}
          {{- with $job.nodeSelector }}
          nodeSelector:
{{ toYaml . | indent 12 }}
          {{- end }}
          {{- with $job.affinity }}
          affinity:
{{ toYaml . | indent 12 }}
          {{- end }}
          {{- with $job.tolerations }}
          tolerations:
{{ toYaml . | indent 12 }}
          {{- end }}
          restartPolicy: {{ $job.restartPolicy }}
          {{- with $job.volumes }}
          volumes:
{{ toYaml . | indent 12 }}
          {{- end }}
  schedule: {{ $job.schedule | quote }}
  successfulJobsHistoryLimit: {{ $job.successfulJobsHistoryLimit }}
{{- end }}