{{- include "adp-helm-library.persistent-volume-claim" (list . "ncea-harvester.persistent-volume-claim") -}}
{{- define "ncea-harvester.persistent-volume-claim" -}}
spec:
  accessModes:
  - ReadWriteMany
{{- end -}}