- key: ApplicationInsights__ConnectionString
  value: "{{servicename}}-APPINSIGHTS-CONNECTIONSTRING"
  type: "keyvault"
- key: ServiceBusHostName
  value: "TSTNCESBINF1401.servicebus.windows.net"
- key: KeyVaultUri
  value: "https://tstnceinfkvt1401.vault.azure.net/"
- key: BlobStorageUri
  value: "https://tstnceinfst1401.blob.core.windows.net"